// Auto-generated preload script
// This file is automatically generated by scripts/preload-critical-modules.js

export const preloadCriticalModules = async () => {
  const modulePromises = [
    import('../components/FileUpload/FileUpload').catch(console.warn),
    import('../components/AnalysisResults/AnalysisResults').catch(console.warn),
    import('../components/LazyComponents').catch(console.warn),
    import('../utils/bundleOptimization').catch(console.warn),
    import('../utils/performance').catch(console.warn),
    import('../utils/errorBoundary').catch(console.warn),
    import('../state/enhancedAppState').catch(console.warn),
    import('../hooks/usePerformanceOptimization').catch(console.warn),
    import('../services/clientService').catch(console.warn),
  ];

  try {
    await Promise.allSettled(modulePromises);
    console.debug('[Preloader] Critical modules preloaded');
  } catch (error) {
    console.warn('[Preloader] Some modules failed to preload:', error);
  }
};

export const CRITICAL_MODULE_NAMES = [
  'FileUpload',
  'AnalysisResults',
  'LazyComponents',
  'bundleOptimization',
  'performance',
  'errorBoundary',
  'enhancedAppState',
  'usePerformanceOptimization',
  'clientService',
];

// Automatically start preloading if this module is imported
if (typeof window !== 'undefined' && window.requestIdleCallback) {
  window.requestIdleCallback(() => {
    preloadCriticalModules();
  }, { timeout: 3000 });
} else if (typeof window !== 'undefined') {
  setTimeout(preloadCriticalModules, 1000);
}

export default preloadCriticalModules;